services:
  node-app:
    build:
      context: .                
      dockerfile: Dockerfile
    container_name: node-service
    environment:
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      - mysql                   

  mysql:
    image: mysql:8.0
    container_name: service_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
